// Generated by hand from the task-manager-sainest Firebase project's
// android/app/google-services.json and ios/Runner/GoogleService-Info.plist
// (no `flutterfire configure` CLI available in this environment). If the
// Firebase project is ever regenerated, re-copy the matching fields from
// those two files rather than editing this by guesswork.
//
// This project lives under a personal Google account, not HQEPL's
// herequality.com Workspace org -- every project under that org has
// iam.disableServiceAccountKeyCreation enforced org-wide (Google's
// "Secure by Default" baseline), which blocks generating the private key
// the backend needs to actually send pushes (see config/firebase.js in
// the server repo). A personal account has no such org policy.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io' show Platform;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('DefaultFirebaseOptions have not been configured for web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform (${Platform.operatingSystem}).',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Ck7xycuITdWPGqWxc4Sh1220WXjxJAU',
    appId: '1:1035923434706:android:ae0bbc9b6928fe20c0110b',
    messagingSenderId: '1035923434706',
    projectId: 'task-manager-sainest',
    storageBucket: 'task-manager-sainest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeF_pF5qplaPdkXvRF7JkmTP5bREjqaGw',
    appId: '1:1035923434706:ios:ad6eddaa783cc82cc0110b',
    messagingSenderId: '1035923434706',
    projectId: 'task-manager-sainest',
    storageBucket: 'task-manager-sainest.firebasestorage.app',
    iosBundleId: 'com.hqepl.taskmanager',
  );
}
